### ISSUE TITLE
是否在未来的开发中增加对字体大小的调整

### ISSUE THREAD

**Issue by ZhaoTim** [Justin3go/justin3go.github.io#114]
博客很好看！
但是字体似乎有点小，想麻烦问下后续会考虑暴露可以调整字体大小的配置项吗？

**Comment by Justin3go** [comment]
谢谢~，这部分使用的是Vitepress的默认字体大小（正文16px，大纲14px...），我看了下[其官方配置项](https://github.com/vuejs/vitepress/blob/main/src/client/theme-default/styles/vars.css)，似乎没有找到可修改全局字体的地方，只有代码字体等少数几处地方的大小可以修改：

![image](https://github.com/user-attachments/assets/c3d3ae96-e25c-433a-b56f-3d87dbd0b9e3)

目前暂时也没想到比较好的解决方案，应该可以尝试字体文件让其等比缩放（没试过）。
