### ISSUE TITLE
[bug]  Navigation bar error

### ISSUE THREAD

**Issue by RSS1102** [Justin3go/justin3go.github.io#49]
When I click here, a redirect will occur, navigating to a non-existent address. You should give it a default value, or the header should not be allowed to be clicked.https://justin3go.com/%E5%8D%9A%E5%AE%A2/2023/

![image](https://github.com/Justin3go/justin3go.github.io/assets/81673017/347b35dd-8aa1-4b9c-993f-0ad39bc66b4d)

**Comment by RSS1102** [comment]
It's the same every month tag.

**Comment by Justin3go** [comment]
新版本的vitepress这里已经修复该问题，点击折叠栏不再跳转页面，现在vitepress已经rc24了，等其发布正式版之后，我会立即同步做一次大更新，该问题将在其正式发布后修复

**Comment by Justin3go** [comment]
刚刚升级到了rc.33版本，只需在sidebar中删除link即可修复该问题：

![image](https://github.com/Justin3go/justin3go.github.io/assets/63507251/4d3c6d93-20f1-4232-8549-ceea9f59c72f)
